projects:
  showcasesocial2-dev:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: e3dv5mtqfvh3njykwr45t34nnu
        maxDepth: 2
extensions:
  amplify:
    version: 3
